### PR TITLE
print_function for py3

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Ping @wjwwood

**Comment by Tobias-Fischer** [comment]
Ping

**Comment by PeterMitrano** [comment]
+1, can confirm this fix is needed and that it works

**Comment by Tobias-Fischer** [comment]
We have a fixed version in https://github.com/RoboStack/ros-noetic

**Review by wjwwood — APPROVED** [review]
lgtm, @mabelzhang I'll let you decide when to merge/release this change.

**Comment by Tobias-Fischer** [comment]
Ping  @mabelzhang - it would be great to get this merged :)

**Comment by mabelzhang** [comment]
Thanks everyone! Sorry for the delay.

**Pull request merged**
