### PR TITLE
add MOVE_ROTATE_3D interactive marker to tutorial

### PR DESCRIPTION
**Pull request by acornacorn**

### CODE REVIEW

**Comment by dgossow** [comment]
Could you please also add this to basic_controls.py?

**Comment by dgossow** [comment]
Also, please update the tutorial: http://www.ros.org/wiki/rviz/Tutorials/Interactive%20Markers%3A%20Basic%20Controls

**Comment by acornacorn** [comment]
I made the following changes:
- move the 3D marker control to the 3rd position, right after the 6DOF controls
- add a second 3D marker which additionally has the 6DOF controls
- update the python version of basic_controls by adding the new markers there too

**Comment by dgossow** [comment]
This is probably superceded by #7. Close?

**Comment by acornacorn** [comment]
Yes, superceded by #7.  Closing.

**Pull request closed without merging**
