### PR TITLE
Port interactive_marker_tutorials to ROS 2

### PR DESCRIPTION
**Pull request by jacobperron**
Porting all interactive marker tutorials except the "point cloud" tutorial, which doesn't appear to demonstrate anything special about interactive markers (it also doesn't appear to have any associated wiki page like the [others tutorials](http://wiki.ros.org/rviz/Tutorials/Interactive%20Markers%3A%20Getting%20Started)).
Instead, I've just removed the tutorial (d36e7b1).

While porting I did some refactoring to try and make the tutorial code more consistent with itself and other ROS 2 packages:

* Each tutorial is implemented as a class inheriting from `rclcpp::Node` (with the exception of simple_marker because it's "simple").
* Following [ROS 2 style guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#language-versions-and-code-format).
* C++14

I've also added COLCON_IGNORE marker files for the other packages in this repository that have not (yet) been ported to ROS 2.

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]
lgtm, that was a long one :)

**Comment by jacobperron** [comment]
> lgtm, that was a long one :)

:bowing_man:

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8211/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4186/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6689/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8092/)

**Comment by jacobperron** [comment]
Requires https://github.com/ros-visualization/interactive_markers/pull/51  to resolve Windows build failure:
[Build Status](https://ci.ros2.org/job/ci_windows/8110/)

Edit: retriggered with 1b6db6b

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
