### PR TITLE
Catkinize groovy-devel

### PR DESCRIPTION
**Pull request by danepowell**
This is just a backport of the catkinization from hydro-devel

### CODE REVIEW

**Comment by hershwg** [comment]
Thanks for the contribution, but I wonder why this is desired?  Are you writing something that uses catkin which depends on these tutorial packages?

**Comment by danepowell** [comment]
Yes, I'm writing a package that makes use of interactive markers and the interactive marker tutorials. I don't know yet that I'll be able to release it publicly, but I wanted it to be catkinized.

**Comment by hershwg** [comment]
@dgossow do you have an opinion on this?  I feel like it is out there and released already and this is a major change.  On the other hand, maybe it doesn't affect much?  Docs need to change?

**Comment by dgossow** [comment]
Usually, you shouldn't make a major change like this that late in the life cycle of a ROS release. I don't think that many packages depend on visualization_tutorials, but it's bad practice. Also, if you're not releasing the packages, you can as well just use them from source with the branch you already created, so I don't see the value of this when there's a danger of causing problems for groovy users.

**Comment by dgossow** [comment]
Maybe @tfoote, @wjwwood or @dirk-thomas will give us directions on how to proceed.

**Comment by wjwwood** [comment]
Is `interactive_markers` catkinized in groovy?

**Comment by hershwg** [comment]
yes: https://github.com/ros-visualization/interactive_markers/blob/groovy-devel/package.xml

**Comment by wjwwood** [comment]
I would say it is completely up to the maintainers, but @dgossow is right to have reservations about updating a package with a potentially breaking change in the middle of a released distro.

**Comment by danepowell** [comment]
It's up to you, I certainly don't want to make life difficult for anyone. But I think the only users affected would be those using visualization_tutorials from src (how many of those can there be?), and they'd just have to move the package to a catkin workspace. Anyway, I defer to your judgments :)

**Comment by tfoote** [comment]
For development I'd suggest just using the hydro branch, as this is basically a backport of the hydro branch.  And then targeting a potential future release against Hydro.

**Comment by dgossow** [comment]
I'd say close. If this blocks you from releasing something into groovy, we'll reconsider.

**Pull request closed without merging**
