### PR TITLE
unified find_package for Qt4 and Qt5

### PR DESCRIPTION
**Pull request by rhaschke**
As the tutorial probably will serve as a template for many other plugins, I suggest this more uniform find_package usage for Qt4 and Qt5.
Also, shouldn't we insist in the very same Qt version, i.e. using `EXACT`?

### CODE REVIEW

**Comment by rhaschke** [comment]
The Travis error seems to be unrelated to my changes: rosdep cannot install `libqt5widgets5`:

```
executing command [sudo -H apt-get install -y libqt5widgets5]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libqt5widgets5
```

**Comment by wjwwood** [comment]
Yeah, I'll have to fix the CI.

**Comment by wjwwood** [comment]
@rhaschke can you rebase this so the CI is fixed?

**Comment by rhaschke** [comment]
@wjwwood Rebased. CI successfully built.

**Comment by wjwwood** [comment]
Thanks.

**Pull request merged**
